title: "Abhishek Kumar"
email: abhimait1909@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am Abhishek, an MLH fellow of Explorer batch and open source developer at Code for cause
url: "/portfolio-template" 
twitter_username: Abhi_dev_dude
github_username:  Abhishek-kumar09

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg